name: guacamayo_marketing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.9.0
  flutter_riverpod: ^2.6.1
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  flutter_stripe: ^11.5.0
  http: ^1.4.0
  logger: ^2.5.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icono.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00AEEF"

flutter_native_splash:
  color: "#00AEEF"
  image: assets/icon/icono.png
  android_12:
    image: assets/icon/icono.png 
    icon_background_color: "#00AEEF" 
  
