// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO5qGVgeGWQqNdm5vDW-6uNRuETEENwvs',
    appId: '1:480962960119:web:2bd62a2386c3b3c02811f2',
    messagingSenderId: '480962960119',
    projectId: 'guacamayo-marketing-solutions',
    authDomain: 'guacamayo-marketing-solutions.firebaseapp.com',
    storageBucket: 'guacamayo-marketing-solutions.firebasestorage.app',
    measurementId: 'G-66GX2L2004',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkIkVE4ttPcBujLKv8Cam3FaTr3150wE',
    appId: '1:480962960119:android:04d97260a2aedeef2811f2',
    messagingSenderId: '480962960119',
    projectId: 'guacamayo-marketing-solutions',
    storageBucket: 'guacamayo-marketing-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoULzImEuFD8YTUHcMu0zvd_8ZFZytQw',
    appId: '1:480962960119:ios:f4233a1cf608e5772811f2',
    messagingSenderId: '480962960119',
    projectId: 'guacamayo-marketing-solutions',
    storageBucket: 'guacamayo-marketing-solutions.firebasestorage.app',
    iosBundleId: 'com.example.guacamayoMarketingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoULzImEuFD8YTUHcMu0zvd_8ZFZytQw',
    appId: '1:480962960119:ios:f4233a1cf608e5772811f2',
    messagingSenderId: '480962960119',
    projectId: 'guacamayo-marketing-solutions',
    storageBucket: 'guacamayo-marketing-solutions.firebasestorage.app',
    iosBundleId: 'com.example.guacamayoMarketingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO5qGVgeGWQqNdm5vDW-6uNRuETEENwvs',
    appId: '1:480962960119:web:95bd14923733378b2811f2',
    messagingSenderId: '480962960119',
    projectId: 'guacamayo-marketing-solutions',
    authDomain: 'guacamayo-marketing-solutions.firebaseapp.com',
    storageBucket: 'guacamayo-marketing-solutions.firebasestorage.app',
    measurementId: 'G-8X64XZR31R',
  );
}
